/**
 * TrainingCircuit — Section 02 interactive centerpiece.
 *
 * DUAL TRACK layout with two parallel boundaries (inner + outer), representing
 * the real limits of the circuit. The animated dot (the car) moves BETWEEN the
 * two lines, oscillating perpendicular to the path (left/right symmetry sway).
 *
 * Each of the 11 sensor rays genuinely reaches the nearest wall boundary —
 * the ray casts from the dot position in its direction and stops at the first
 * hit on either the inner or outer HALO stroke (thicker invisible path used
 * purely for hit testing). Perpendicular rays therefore look short (near wall)
 * and forward rays look long (open road).
 *
 * Offset paths are generated by UNIFORM SAMPLING of the centerline via
 * `getPointAtLength`, NOT by tokenizing the raw M/L commands. Raw paths with
 * many tiny line segments cause noisy normals; uniform sampling gives smooth,
 * continuous offset curves.
 *
 * Auto-generated checkpoints pulse at fixed t values along the path.
 * A scrub slider pauses the auto-animation and lets the user position the
 * dot manually.
 *
 * Honours `prefers-reduced-motion`: dot stays at scrub=0 with full rays;
 * the slider still works for manual scrubbing.
 */
import { useEffect, useMemo, useRef, useState } from 'react';
import type { ChangeEvent } from 'react';
import circuitsRaw from '../../data/circuits/circuits.json';
import type { Circuit } from '../../data/circuits';

interface Props {
  locale: 'es' | 'en';
}

// Single source-of-truth for the rendered circuit
const RAW = circuitsRaw as unknown as Record<string, { length_m: number; path_d: string }>;
const TRAINING_CIRCUIT: Circuit = {
  id: 'training',
  nameEs: 'Circuito de entrenamiento',
  nameEn: 'Training circuit',
  countryEs: '',
  countryEn: '',
  lengthKm: Math.round(RAW.barcelona.length_m / 10) / 100, // 4.656 → 4.66
  turns: 16,
  yearActive: 2024,
  pathD: RAW.barcelona.path_d,
  totalCheckpoints: 12,
};

// ViewBox — slightly different aspect to keep the SVG crisp.
const VB_W = 720;
const VB_H = 432;
const PAD = { l: 28, r: 28, t: 28, b: 28 };
const PLOT_W = VB_W - PAD.l - PAD.r;
const PLOT_H = VB_H - PAD.t - PAD.b;

// Source path geometry
const SRC_W = 400;
const SRC_H = 240;

function scaleX(x: number): number {
  return PAD.l + (x / SRC_W) * PLOT_W;
}
function scaleY(y: number): number {
  return PAD.t + (y / SRC_H) * PLOT_H;
}

/** Re-emit the source path scaled into the outer viewBox. */
function transformPath(sourceD: string): string {
  let out = '';
  const tokens = sourceD.match(/[MLZ]|-?\d+\.?\d*/g) ?? [];
  for (let i = 0; i < tokens.length; ) {
    const t = tokens[i]!;
    if (t === 'M' || t === 'L' || t === 'Z') {
      out += ` ${t}`;
      i++;
    } else {
      const x = parseFloat(t);
      const y = parseFloat(tokens[i + 1]!);
      out += ` ${scaleX(x).toFixed(2)} ${scaleY(y).toFixed(2)}`;
      i += 2;
    }
  }
  return out.trim();
}

// ---------------------------------------------------------------------------
// Auto-animation parameters
// ---------------------------------------------------------------------------

/** One full lap in milliseconds.
 *
 * Tuned to ≈66 s end-to-end so the dot transit feels closer to the
 * step-by-step evolution of the trained policy. The previous value (13 s)
 * was handy for a quick visual scan but read as a sped-up replay rather than
 * a faithful render of the model output. Increased 2026-09-21.
 */
const AUTO_LAP_DURATION_MS = 66_000;

/** After the user touches the slider, auto-animation pauses for this long. */
const USER_OVERRIDE_TIMEOUT_MS = 3_000;

// ---------------------------------------------------------------------------
// Track geometry — dual boundaries
// ---------------------------------------------------------------------------

/** Half-width of the track surface (distance from centerline to each wall).
 *
 * Geometric reason for the value (was 22, reduced to 10 on 2026-09-21):
 *  - With the forward-tangent / 240-sample normal computation, the offset
 *    path's half-width must stay below the centreline's local "self-distance"
 *    (min distance between two non-adjacent samples) at every point,
 *    otherwise the inner boundary self-intersects when the path doubles back
 *    on itself (the tight top-left hairpin around sample 173, plus three
 *    other bends). The previous value (22 vb) gave 4 inner + 2 outer
 *    self-intersections, which rendered as visible scribbles inside the
 *    track outline. 10 vb brings both counts to zero.
 *  - The dot oscillation `oscAmp = HALF * 0.55` (5.5 vb) stays well within
 *    the narrowed walls at every sweep, and the 130 vb ray-cap still
 *    comfortably reaches the boundary.
 */
const TRACK_HALF_WIDTH = 10;

/** Halo stroke width — invisible thick strokes used for hit testing rays. */
const HALO_STROKE_WIDTH = 8;

/** Number of uniform samples used to compute offset paths. Higher = smoother. */
const OFFSET_SAMPLES = 240;

// ---------------------------------------------------------------------------
// 11 sensor rays — spec says "11 rayos sensor" in the headline copy, so
// we hard-wire 11 rays from the dot's position, fanned 180° across the
// forward hemisphere relative to the path tangent.
// ---------------------------------------------------------------------------
const N_RAYS = 11;
const RAY_SPREAD_DEG = 180;
const RAY_MAX_LENGTH = 130;

/** Sample distance for the path tangent (in viewBox units). */
const TANGENT_DELTA = 1.2;

/** Length of the small trail behind the dot, in viewBox units. */
const TAIL_LENGTH = 14;

// Checkpoints — 12 evenly distributed dots along the path
const CHECKPOINT_T = Array.from({ length: 12 }, (_, i) => (i + 0.5) / 12);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface SampledPoint {
  x: number;
  y: number;
  /** Forward unit tangent (toward the next sample). */
  tx: number;
  ty: number;
  /** Left-perpendicular unit normal (counter-clockwise 90°). */
  nx: number;
  ny: number;
}

/**
 * Sample the centerline UNIFORMLY along its arc length using `getPointAtLength`.
 * For each sample, derive the forward tangent (next-sample direction) and the
 * left-perpendicular unit normal. Closes the loop at sample N == 0.
 */
function sampleCenterline(
  path: SVGPathElement,
  n: number
): SampledPoint[] {
  const len = path.getTotalLength();
  const pts: SampledPoint[] = new Array(n);
  const raw: { x: number; y: number }[] = new Array(n);
  for (let i = 0; i < n; i++) {
    const p = path.getPointAtLength((i / n) * len);
    raw[i] = { x: p.x, y: p.y };
  }
  for (let i = 0; i < n; i++) {
    const curr = raw[i]!;
    const next = raw[(i + 1) % n]!;
    const dx = next.x - curr.x;
    const dy = next.y - curr.y;
    const m = Math.sqrt(dx * dx + dy * dy) || 1;
    const tx = dx / m;
    const ty = dy / m;
    pts[i] = {
      x: curr.x,
      y: curr.y,
      tx,
      ty,
      nx: -ty, // rotate tangent 90° CCW → left-perpendicular
      ny: tx,
    };
  }
  return pts;
}

/** Build a smooth offset path string from sampled points. */
function buildOffsetPath(samples: SampledPoint[], offset: number): string {
  let out = '';
  for (let i = 0; i < samples.length; i++) {
    const s = samples[i]!;
    const x = s.x + s.nx * offset;
    const y = s.y + s.ny * offset;
    out += i === 0 ? `M ${x.toFixed(2)} ${y.toFixed(2)}` : ` L ${x.toFixed(2)} ${y.toFixed(2)}`;
  }
  out += ' Z';
  return out;
}

function isInsideStroke(path: SVGPathElement, x: number, y: number): boolean {
  // isPointInStroke requires a DOMPointInit object, not raw (x,y) numbers,
  // in modern Chrome/Edge. SVGPoint (via createSVGPoint) is the cross-browser
  // way to satisfy the signature — supported by Safari too.
  const svg = path.ownerSVGElement;
  if (!svg) return false;
  const pt = svg.createSVGPoint();
  pt.x = x;
  pt.y = y;
  return path.isPointInStroke(pt);
}

interface Ray {
  x2: number;
  y2: number;
  actualLength: number;
}

/**
 * Cast a ray from (ox, oy) in direction (dirX, dirY) until it hits either
 * `innerHalo` or `outerHalo`. Returns the hit position relative to the origin
 * (so x2,y2 are in the car's local frame).
 *
 * Halos use a thick stroke (HALO_STROKE_WIDTH), so hits are robust even with
 * low step sizes.
 */
function castRayToBoundary(
  ox: number,
  oy: number,
  dirX: number,
  dirY: number,
  innerHalo: SVGPathElement,
  outerHalo: SVGPathElement,
  maxLen: number,
  step: number
): Ray {
  for (let dist = step; dist <= maxLen; dist += step) {
    const sx = ox + dirX * dist;
    const sy = oy + dirY * dist;

    if (isInsideStroke(innerHalo, sx, sy) || isInsideStroke(outerHalo, sx, sy)) {
      return { x2: dirX * dist, y2: dirY * dist, actualLength: dist };
    }
  }
  return { x2: dirX * maxLen, y2: dirY * maxLen, actualLength: maxLen };
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function TrainingCircuit({ locale }: Props) {
  const pathRef = useRef<SVGPathElement | null>(null);
  const innerVisibleRef = useRef<SVGPathElement | null>(null);
  const outerVisibleRef = useRef<SVGPathElement | null>(null);
  const innerHaloRef = useRef<SVGPathElement | null>(null);
  const outerHaloRef = useRef<SVGPathElement | null>(null);
  const carGroupRef = useRef<SVGGElement | null>(null);
  const tailRef = useRef<SVGLineElement | null>(null);

  const [scrub, setScrub] = useState<number>(0);
  const [pathLength, setPathLength] = useState<number>(0);
  const [samples, setSamples] = useState<SampledPoint[]>([]);
  const [rays, setRays] = useState<Ray[]>(() =>
    Array.from({ length: N_RAYS }, () => ({ x2: 0, y2: 0, actualLength: RAY_MAX_LENGTH }))
  );

  // Pulse animation for checkpoints
  const [pulseOn, setPulseOn] = useState<boolean>(true);
  useEffect(() => {
    const interval = window.setInterval(() => setPulseOn((v) => !v), 1100);
    return () => window.clearInterval(interval);
  }, []);

  // -------------------------------------------------------------------
  // Animation loop — refs so updates don't trigger re-renders.
  // -------------------------------------------------------------------
  const scrubRef = useRef<number>(0);
  const lastFrameTimeRef = useRef<number>(0);
  const rafRef = useRef<number | null>(null);
  const lastUserInputTimeRef = useRef<number>(0);
  const prefersReducedMotionRef = useRef<boolean>(false);

  // Watch prefers-reduced-motion and update the ref when the OS setting flips.
  useEffect(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return;
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    prefersReducedMotionRef.current = mq.matches;
    const handler = (e: MediaQueryListEvent) => {
      prefersReducedMotionRef.current = e.matches;
    };
    if (mq.addEventListener) {
      mq.addEventListener('change', handler);
      return () => mq.removeEventListener('change', handler);
    }
    // eslint-disable-next-line @typescript-eslint/no-deprecated
    mq.addListener(handler);
    return () => {
      // eslint-disable-next-line @typescript-eslint/no-deprecated
      mq.removeListener(handler);
    };
  }, []);

  // Measure path length, sample it, and place the dot at the start of the
  // track before the first animation frame (so there's no flash at (0,0)).
  useEffect(() => {
    const p = pathRef.current;
    if (!p) return;
    const len = p.getTotalLength();
    setPathLength(len);

    const s = sampleCenterline(p, OFFSET_SAMPLES);
    setSamples(s);

    // Seed the car at t=0 with the correct tangent.
    if (s.length > 0 && carGroupRef.current) {
      const first = s[0]!;
      carGroupRef.current.setAttribute(
        'transform',
        `translate(${first.x.toFixed(2)} ${first.y.toFixed(2)})`
      );
      // Tail initially points backward along the tangent.
      if (tailRef.current) {
        tailRef.current.setAttribute('x2', (-first.tx * TAIL_LENGTH).toFixed(2));
        tailRef.current.setAttribute('y2', (-first.ty * TAIL_LENGTH).toFixed(2));
      }
    }
  }, []);

  // Pre-compute checkpoint positions
  const checkpoints = useMemo(() => {
    if (samples.length === 0) return [];
    const n = samples.length;
    return CHECKPOINT_T.map((t) => {
      const idx = Math.floor(t * n) % n;
      const s = samples[idx]!;
      return { x: s.x, y: s.y };
    });
  }, [samples]);

  // Pre-compute the offset path strings.
  const { innerD, outerD } = useMemo(() => {
    if (samples.length === 0) return { innerD: '', outerD: '' };
    return {
      innerD: buildOffsetPath(samples, -TRACK_HALF_WIDTH),
      outerD: buildOffsetPath(samples, TRACK_HALF_WIDTH),
    };
  }, [samples]);

  /**
   * Compute the 11 rays (and update car position + tail) for a given scrub
   * value. The dot position oscillates perpendicular to the local tangent
   * using a sinusoidal phase derived from scrub.
   */
  const updateVisuals = (scrubVal: number): void => {
    if (samples.length === 0) return;
    const n = samples.length;
    // Clamp scrub into [0, 1); the lerp below wraps automatically.
    const pos = ((scrubVal % 1) + 1) % 1;
    const idxF = pos * n;
    const i0 = Math.floor(idxF) % n;
    const i1 = (i0 + 1) % n;
    const f = idxF - Math.floor(idxF);
    const a = samples[i0]!;
    const b = samples[i1]!;
    const baseX = a.x + (b.x - a.x) * f;
    const baseY = a.y + (b.y - a.y) * f;
    const tangentAngle = Math.atan2(b.y - a.y, b.x - a.x);

    // Perpendicular = tangent - 90°
    const normalAngle = tangentAngle - Math.PI / 2;

    // Oscillation around the centerline with amplitude 60% of half-width
    const oscPhase = scrubVal * Math.PI * 6; // 3 oscillations per lap
    const oscAmp = TRACK_HALF_WIDTH * 0.55;
    const dotOffset = Math.sin(oscPhase) * oscAmp;
    const dotX = baseX + Math.cos(normalAngle) * dotOffset;
    const dotY = baseY + Math.sin(normalAngle) * dotOffset;

    const innerHalo = innerHaloRef.current;
    const outerHalo = outerHaloRef.current;
    if (!innerHalo || !outerHalo) return;

    const half = RAY_SPREAD_DEG / 2;
    const newRays: Ray[] = new Array(N_RAYS);
    for (let i = 0; i < N_RAYS; i++) {
      const spreadDeg = -half + (i * RAY_SPREAD_DEG) / (N_RAYS - 1);
      const rayAngle = tangentAngle + (spreadDeg * Math.PI) / 180;
      const dirX = Math.cos(rayAngle);
      const dirY = Math.sin(rayAngle);
      newRays[i] = castRayToBoundary(
        dotX,
        dotY,
        dirX,
        dirY,
        innerHalo,
        outerHalo,
        RAY_MAX_LENGTH,
        2
      );
    }

    setRays(newRays);

    if (carGroupRef.current) {
      carGroupRef.current.setAttribute(
        'transform',
        `translate(${dotX.toFixed(2)} ${dotY.toFixed(2)})`
      );
    }
    if (tailRef.current) {
      tailRef.current.setAttribute('x2', (-Math.cos(tangentAngle) * TAIL_LENGTH).toFixed(2));
      tailRef.current.setAttribute('y2', (-Math.sin(tangentAngle) * TAIL_LENGTH).toFixed(2));
    }
  };

  // Main rAF loop
  useEffect(() => {
    if (samples.length === 0) return;
    let stopped = false;
    const animate = (now: number) => {
      if (stopped) return;
      const dt = lastFrameTimeRef.current === 0 ? 0 : now - lastFrameTimeRef.current;
      lastFrameTimeRef.current = now;
      const timeSinceUserInput = now - lastUserInputTimeRef.current;
      const shouldAutoPlay =
        !prefersReducedMotionRef.current &&
        timeSinceUserInput > USER_OVERRIDE_TIMEOUT_MS;
      if (shouldAutoPlay) {
        const advance = dt / AUTO_LAP_DURATION_MS;
        let newScrub = scrubRef.current + advance;
        if (newScrub >= 1) newScrub -= 1;
        scrubRef.current = newScrub;
        setScrub(newScrub);
      }
      updateVisuals(scrubRef.current);
      rafRef.current = requestAnimationFrame(animate);
    };
    rafRef.current = requestAnimationFrame(animate);
    return () => {
      stopped = true;
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [samples]);

  // Slider → overrides auto-animation for 3 s, then auto resumes.
  const handleSliderChange = (e: ChangeEvent<HTMLInputElement>) => {
    const newScrub = Number(e.target.value) / 100;
    scrubRef.current = newScrub;
    setScrub(newScrub);
    lastUserInputTimeRef.current = performance.now();
  };

  const labels = {
    caption:
      locale === 'es'
        ? 'Once rayos sensor detectan bordes y línea de meta desde la posición del coche.'
        : 'Eleven sensor rays detect edges and finish line from the car position.',
    scrub: locale === 'es' ? 'Posición' : 'Position',
    checkpointsLabel:
      locale === 'es' ? 'Checkpoints auto-generados' : 'Auto-generated checkpoints',
    raysLabel: locale === 'es' ? 'Rayos sensor' : 'Sensor rays',
    pathLength: locale === 'es' ? 'Longitud' : 'Length',
    compoundTire: locale === 'es' ? 'Compuesto' : 'Compound',
    lengthValue: TRAINING_CIRCUIT.lengthKm.toFixed(2),
    lengthUnit: 'km',
    compound: 'Soft',
  };

  const showCircuit = innerD !== '' && outerD !== '';
  const showCar = showCircuit;

  return (
    <div className="training-circuit">
      <svg
        className="training-circuit__svg"
        viewBox={`0 0 ${VB_W} ${VB_H}`}
        preserveAspectRatio="xMidYMid meet"
        role="img"
        aria-label={
          locale === 'es'
            ? 'Circuito de entrenamiento simplificado'
            : 'Simplified training circuit'
        }
      >
        <defs>
          <radialGradient id="training-car-halo" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="var(--accent)" stopOpacity="0.5" />
            <stop offset="100%" stopColor="var(--accent)" stopOpacity="0" />
          </radialGradient>
          <filter id="ray-glow" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur in="SourceGraphic" stdDeviation="1.6" result="blur" />
            <feMerge>
              <feMergeNode in="blur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>

        {/* Subtle telemetry grid */}
        <g aria-hidden="true" opacity="0.35">
          {Array.from({ length: 11 }, (_, i) => (
            <line
              key={`vx-${i}`}
              x1={PAD.l + (i / 10) * PLOT_W}
              x2={PAD.l + (i / 10) * PLOT_W}
              y1={PAD.t}
              y2={PAD.t + PLOT_H}
              stroke="var(--rule)"
              strokeWidth={0.5}
              strokeDasharray="1 6"
              vectorEffect="non-scaling-stroke"
            />
          ))}
          {Array.from({ length: 7 }, (_, i) => (
            <line
              key={`hy-${i}`}
              y1={PAD.t + (i / 6) * PLOT_H}
              y2={PAD.t + (i / 6) * PLOT_H}
              x1={PAD.l}
              x2={PAD.l + PLOT_W}
              stroke="var(--rule)"
              strokeWidth={0.5}
              strokeDasharray="1 6"
              vectorEffect="non-scaling-stroke"
            />
          ))}
        </g>

        {/* Track surface fill — asphalt band between inner and outer boundaries */}
        {showCircuit && (
          <>
            <path
              d={`${outerD} L ${samples[0]!.x + samples[0]!.nx * -TRACK_HALF_WIDTH} ${
                samples[0]!.y + samples[0]!.ny * -TRACK_HALF_WIDTH
              } Z`}
              fill="var(--ink)"
              opacity={0.22}
              stroke="none"
              aria-hidden="true"
            />
          </>
        )}

        {/* Inner boundary (left wall, closer to centerline inside) */}
        {showCircuit && (
          <path
            ref={innerVisibleRef}
            d={innerD}
            fill="none"
            stroke="var(--asphalt)"
            strokeWidth={1.2}
            strokeOpacity={0.7}
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          />
        )}

        {/* Outer boundary (right wall) */}
        {showCircuit && (
          <path
            ref={outerVisibleRef}
            d={outerD}
            fill="none"
            stroke="var(--asphalt)"
            strokeWidth={1.2}
            strokeOpacity={0.7}
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          />
        )}

        {/* Centerline path — faint reference line */}
        <path
          ref={pathRef}
          d={transformPath(TRAINING_CIRCUIT.pathD)}
          fill="none"
          stroke="var(--secondary)"
          strokeWidth={1}
          strokeOpacity={0.35}
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        />

        {/* Invisible halos for ray hit detection (thick stroke) */}
        {showCircuit && (
          <path
            ref={innerHaloRef}
            d={innerD}
            fill="none"
            stroke="#000"
            strokeOpacity={0}
            strokeWidth={HALO_STROKE_WIDTH}
            strokeLinecap="round"
            strokeLinejoin="round"
            pointerEvents="none"
            aria-hidden="true"
          />
        )}
        {showCircuit && (
          <path
            ref={outerHaloRef}
            d={outerD}
            fill="none"
            stroke="#000"
            strokeOpacity={0}
            strokeWidth={HALO_STROKE_WIDTH}
            strokeLinecap="round"
            strokeLinejoin="round"
            pointerEvents="none"
            aria-hidden="true"
          />
        )}

        {/* Auto-generated checkpoints */}
        {checkpoints.map((c, i) => (
          <g key={`cp-${i}`}>
            <circle
              cx={c.x}
              cy={c.y}
              r={pulseOn ? 3.5 : 2.5}
              fill="var(--accent)"
              opacity={pulseOn ? 0.9 : 0.5}
              style={{
                transition:
                  'r 0.6s var(--motion-ease-out), opacity 0.6s var(--motion-ease-out)',
              }}
            />
            <circle
              cx={c.x}
              cy={c.y}
              r={pulseOn ? 7 : 5}
              fill="none"
              stroke="var(--accent)"
              strokeWidth={0.7}
              opacity={pulseOn ? 0.4 : 0.15}
              style={{
                transition:
                  'r 0.6s var(--motion-ease-out), opacity 0.6s var(--motion-ease-out)',
              }}
            />
          </g>
        ))}

        {/* The car + sensor rays share a moving group so they translate together. */}
        <g ref={carGroupRef} opacity={showCar ? 1 : 0}>
          {/* Halo */}
          <circle
            cx={0}
            cy={0}
            r={20}
            fill="url(#training-car-halo)"
            aria-hidden="true"
          />

          {/* 11 sensor rays — cast from the dot to the nearest wall */}
          <g filter="url(#ray-glow)">
            {rays.map((r, i) => (
              <line
                key={`ray-${i}`}
                x1={0}
                y1={0}
                x2={r.x2}
                y2={r.y2}
                stroke="var(--secondary)"
                strokeWidth={3}
                strokeDasharray="5 5"
                strokeLinecap="round"
                opacity={0.9}
                vectorEffect="non-scaling-stroke"
                aria-hidden="true"
              />
            ))}
          </g>

          {/* Speed tail */}
          <line
            ref={tailRef}
            x1={0}
            y1={0}
            x2={0}
            y2={0}
            stroke="var(--accent)"
            strokeWidth={1.6}
            opacity={0.45}
            strokeLinecap="round"
            vectorEffect="non-scaling-stroke"
            aria-hidden="true"
          />

          {/* Outer halo ring */}
          <circle cx={0} cy={0} r={7} fill="var(--accent)" opacity={0.18} aria-hidden="true" />

          {/* The dot itself */}
          <circle cx={0} cy={0} r={4.5} fill="var(--accent)" stroke="var(--ink)" strokeWidth={1.5} />
        </g>
      </svg>

      {/* HUD overlay */}
      <div className="training-circuit__hud" aria-hidden="true">
        <div className="training-circuit__stat">
          <span className="training-circuit__stat-value">
            {TRAINING_CIRCUIT.totalCheckpoints}
          </span>
          <span className="training-circuit__stat-label">{labels.checkpointsLabel}</span>
        </div>
        <div className="training-circuit__stat">
          <span className="training-circuit__stat-value">{N_RAYS}</span>
          <span className="training-circuit__stat-label">{labels.raysLabel}</span>
        </div>
        <div className="training-circuit__stat">
          <span className="training-circuit__stat-value">{labels.lengthValue}</span>
          <span className="training-circuit__stat-label">
            {labels.pathLength} ({labels.lengthUnit})
          </span>
        </div>
        <div className="training-circuit__stat">
          <span className="training-circuit__stat-value">{labels.compound}</span>
          <span className="training-circuit__stat-label">{labels.compoundTire}</span>
        </div>
      </div>

      {/* Manual scrub slider */}
      <div className="training-circuit__scrub">
        <label className="training-circuit__scrub-label" htmlFor="training-circuit-scrub">
          <span>{labels.scrub}</span>
          <span className="training-circuit__scrub-pos">
            {(scrub * 100).toFixed(0)}%
          </span>
        </label>
        <input
          id="training-circuit-scrub"
          type="range"
          min={0}
          max={100}
          step={0.25}
          value={scrub * 100}
          onChange={handleSliderChange}
          className="training-circuit__scrub-range"
          aria-label={labels.scrub}
        />
        <div className="training-circuit__scrub-axis" aria-hidden="true">
          <span>0</span>
          <span>50</span>
          <span>100</span>
        </div>
      </div>

      <p className="training-circuit__caption">{labels.caption}</p>
    </div>
  );
}
